---
name: concourse

releases:
  - name: concourse
    url: https://bosh.io/d/github.com/concourse/concourse?v=0.74.0
    sha1: c99ef709e9d4468ac25cca31dd5be1444417011d
  - name: garden-linux
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/garden-linux-release?v=0.334.0
    sha1: 85170c5089fa4ff317f139c2f1da024860dbea85
  - name: bosh-aws-cpi
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=44
    sha1: a1fe03071e8b9bf1fa97a4022151081bf144c8bc

resource_pools:
  - name: concourse
    network: concourse
    stemcell:
      url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3189
      sha1: 959736b3c9aa9c649f8299c6192dc9840cf4a7dd
    cloud_properties:
      instance_type: m3.xlarge
      availability_zone: us-west-1a
      elbs: [concourse]

disk_pools:
  - name: db
    disk_size: 10240
    cloud_properties:
      type: gp2

networks:
  - name: concourse
    type: manual
    subnets:
      - range: 10.0.16.0/20
        dns: [10.0.0.2]
        gateway: 10.0.16.1
        cloud_properties:
          security_groups: [concourse]
          subnet: SUBNET_ID
  - name: public
    type: vip

jobs:
  - name: concourse
    instances: 1
    resource_pool: concourse
    persistent_disk_pool: db

    templates:
      - {release: concourse, name: atc}
      - {release: concourse, name: groundcrew}
      - {release: concourse, name: tsa}
      - {release: concourse, name: baggageclaim}
      - {release: garden-linux, name: garden}

    networks:
      - name: public
        static_ips: [ELASTIC_IP]
      - name: concourse
        static_ips: [10.0.16.11]
        default: [dns, gateway]

    properties:
      atc:
        basic_auth_username: &atc_username USERNAME
        basic_auth_password: &atc_password PASSWORD
        postgresql:
          address: RDSADDRESS
          database: DATABASENAME
          role:
            name: RDSUSERNAME
            password: RDSPASSWORD
      tsa:
        forward_host: 127.0.0.1
        atc:
          address: 127.0.0.1:8080
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
      groundcrew:
        tsa:
          host: 127.0.0.1

cloud_provider:
  template: {name: aws_cpi, release: bosh-aws-cpi}

  ssh_tunnel:
    host: ELASTIC_IP
    port: 22
    user: vcap
    private_key: PRIVATE_KEY_FILE # Appears to be relative to working dir

  mbus: "https://mbus:mbus-password@ELASTIC_IP:6868"

  properties:
    aws:
      access_key_id: ACCESS_KEY_ID
      secret_access_key: SECRET_ACCESS_KEY
      default_key_name: SSH_KEY_PAIR_NAME
      default_security_groups: [concourse]
      region: us-west-1
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: [0.pool.ntp.org, 1.pool.ntp.org]
