resources:
- name: my-product
  type: git
  source:
    uri: git@github.com:my-user/my-product.git
    branch: master
    private_key: ""

- name: version
  type: semver
  source:
    bucket: my-product-pipeline-artifacts
    initial_version: 1.0.0
    key: current-version
    access_key_id: ""
    secret_access_key: ""

- name: my-product-rc
  type: s3
  source:
    bucket: my-product-pipeline-artifacts
    regexp: my-product-(.*).tgz
    access_key_id: ""
    secret_access_key: ""

- name: my-product-final
  type: s3
  source:
    bucket: my-product
    regexp: my-product-(.*).tgz
    access_key_id: ""
    secret_access_key: ""

jobs:
- name: unit
  plan:
  - get: my-product
    trigger: true
  - task: unit
    file: my-product/ci/unit.yml

- name: build-rc
  serial_groups:
  - version
  plan:
  - get: my-product
    passed: [unit]
    trigger: true
  - get: version
    params: {pre: rc}
  - task: build-artifact
    file: my-product/ci/build-artifact.yml
  - put: my-product-rc
    params: {file: build-artifact/my-product-*.tgz}
  - put: version
    params: {file: version/version}

- name: integration
  serial: true
  plan:
  - get: my-product-rc
    passed: [build-rc]
    trigger: true
  - get: my-product
    passed: [build-rc]
  - task: integration
    file: my-product/ci/integration.yml
    config:
      params:
        ACCESS_KEY: ""
        API_ENDPOINT: ""

- name: shipit
  serial_groups: [version]
  plan:
  - get: my-product-rc
    passed: [integration]
  - get: my-product
    passed: [integration]
  - get: version
    params: {bump: final}
  - task: promote-to-final
    file: my-product/ci/promote-to-final.yml
  - put: my-product-final
    params: {file: promote-to-final/my-product-.*.tgz}
  - put: version
    params: {file: version/version}

- name: major
  plan:
  - put: version
    params: {bump: major, pre: rc}

- name: minor
  plan:
  - put: version
    params: {bump: minor, pre: rc}

- name: patch
  plan:
  - get: version
    passed: [shipit]
    trigger: true
  - put: version
    params: {bump: minor, pre: rc}
